Wcontrols: 1
var_tipo:
  - 2
  - 1
simulador: 1
delsim: 1
par_imex: 8
q_prod:
  - 0
  - 0
q_inj:
  - 500
  - 800
bhp_prod:
  - 36000
  - 38000
bhp_inj:
  - 100
  - 200
t_concessao: 20
num_prod: 20
num_inj: 10
control_steps: 10
delta1: 0.15
delta2: 0.25
temporal: 5
ac1: "templates/Egg_model.tpl"
ac7: "templates/Egg_Report.tpl"
ac2: "Data"
window_size: 30
tpl_time_skip: 100
time_estabilize: 0
sim_time: 1900
generate_tpl: true
executa_imex: 'C:\"Program Files"\CMG\IMEX\2023.10\Win_x64\EXE\mx202310.exe -f '
executa_report: '"C:\Program Files\CMG\RESULTS\2023.10\Win_x64\exe\report.exe" -f  '
