Wcontrols: 1
var_tipo:
  - 2
  - 1
simulator: true
delsim: true
par_imex: 8
q_prod:
  - 0
  - 0
# agua
q_inj:
  - 3000
  - 3500
# gas
q_inj_wag:
  - 1.5e+8
  - 1.8e+8
bhp_prod:
  - 3700
  - 3800
bhp_inj:
  - 100
  - 200
bhp_inj_wag:
  - 0.0001
  - 0.0001
t_concessao: 0
num_prod: 9
num_inj: 4
control_steps: 10
delta1: 0.10
delta2: 0.15
temporal: 2
ac1: "templates/WAG_header.tpl"
ac7: "templates/Wag_Report.tpl"
ac2: "Data"
window_size: 5
time_estabilize: 0
sim_time: 1900
generate_tpl: true
executa_imex: 'gm202310.exe -f '
executa_report: 'report.exe -f  '
wag: true
npw: 1
delta_start: 0.1 # não pode ser maior que o window_size
tpl_time_skip: 100

