Wcontrols: 1
var_tipo:
  - 2
  - 1
simulador: 1
run_simulator: true
delsim: 0
par_imex: 8
q_prod:
  - 0
  - 0
q_inj:
  - 1000.0001
  - 1500.0001
q_inj_wag:
  - 500
  - 3500
bhp_prod:
  - 800
  - 1000
bhp_inj:
  - 100
  - 200
bhp_inj_wag:
  - 0.0001
  - 0.0001
t_concessao: 0
num_prod: 9
num_inj: 4
control_steps: 10
delta1: 0.15
delta2: 0.25
temporal: 5
ac1: "templates/WAG_Mwells_header.tpl"
ac7: "templates/WAG_Report.tpl"
ac2: "Data"
window_size: 5
time_estabilize: 0
sim_time: 1900
generate_tpl: true
executa_imex: '"C:\Program Files\CMG\GEM\2023.10\Win_x64\EXE\gm202310.exe" -f '
executa_report: '"C:\Program Files\CMG\RESULTS\2023.10\Win_x64\exe\report.exe" -f  '
wag: true
npw: 1
delta_start: 0.1 # não pode ser maior que o window_size
tpl_time_skip: 100

